name: Build Workflow

on:
  push:
    branches:
      - '*' 

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set tag name from branch
        run: echo "TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: |
          python -m PyInstaller pdfsplitter.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows_pdfsplitter
          path: dist/pdfsplitter.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body_path: README.md
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/pdfsplitter.exe
          asset_name: pdfsplitter-amd64.exe
          asset_content_type: application/zip
